version: '3.8'

services:
  # Django application container
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:7500
    volumes:
      - .:/app
    ports:
      - "7500:7500"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=boardish
      - DB_USER=bog
      - DB_PASSWORD=backtothebog
      - REDIS_URL=redis://redis:6379/0
    networks:
      - app-network

  # PostgreSQL database container
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=boardish
      - POSTGRES_USER=bog
      - POSTGRES_PASSWORD=backtothebog
    networks:
      - app-network

  # redis for websockets
  redis:
    image: redis:8
    ports:
      - "6379:6379"
    networks:
      - app-network
  
  # worker for daphne
 # worker:
 #   build:
 #     context: .
 #     dockerfile: Dockerfile
 #   command: python manage.py runworker daphne
 #   volumes:
 #     - .:/code
 #   environment:
 #     DJANGO_SETTINGS_MODULE: boardish.settings
 #     REDIS_URL: redis://redis:6379/0
 #   depends_on:
 #     - web
 #     - redis
 #   networks:
 #     - app-network

# Volumes to persist data
volumes:
  postgres_data:

# Networks
networks:
  app-network:
    driver: bridge
