version: '3.8'

services:
  # Django application container
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:7500
    volumes:
      - .:/app
    ports:
      - "7500:7500"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=boardish
      - DB_USER=bog
      - DB_PASSWORD=backtothebog
    networks:
      - app-network

  # PostgreSQL database container
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=boardish
      - POSTGRES_USER=bog
      - POSTGRES_PASSWORD=backtothebog
    networks:
      - app-network

# Volumes to persist data
volumes:
  postgres_data:

# Networks
networks:
  app-network:
    driver: bridge
