# Generated by Django 5.1.4 on 2025-01-09 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('w', models.IntegerField(default=1)),
                ('h', models.IntegerField(default=1)),
                ('type', models.CharField(choices=[('button', 'Button'), ('form', 'Form'), ('image', 'Image'), ('clock', 'Clock'), ('paint', 'Paint'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('data', models.JSONField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ManyToManyField(related_name='boards', through='boards.UserBoard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BoardElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.element')),
            ],
            options={
                'unique_together': {('board', 'element')},
            },
        ),
    ]
