# Generated by Django 5.1.4 on 2025-01-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_element_board_element_order_delete_boardelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
